version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/pi/homeassistant:/config
    environment:
      - TZ=America/New_York
    restart: on-failure
    network_mode: host
  mqtt:
    container_name: mqtt
    hostname: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - /home/pi/mosquitto/config:/mqtt/config:ro
      - /home/pi/mosquitto/log:/mqtt/log
      - /home/pi/mosquitto/data/:/mqtt/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    restart: on-failure
  zmod:
    container_name: zmod
    image: zmod2mqtt:latest
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    depends_on:
      - mqtt
    environment:
      - TZ=America/New_York
    restart: on-failure

